    </section>
</div>

<section class="summit-band" data-summit-band-background="rich-black" data-summit-band-collapse="both">
      <div class="summit-band-container">
          <section class="summit-band-content">
              <footer class="summit-band-footer" data-summit-layout="flex-footer-variant" data-summit-theme="dark">
                  <div class="summit-image-embed">
                      <div class="summit-image-embed-container">
                              
        <div class="media media-element-container media-default"><img class="media-element file-default summit-image-embed-img" alt="Red Hat Shadowman logo" title="redhat.com" src="/gg/images/shadowman-logo.png" width="138" height="44"></div>
                          </a>
                      </div>
                  </div>
                  <div class="summit-group">
                      <div class="summit-group-body" data-summit-layout="flex-center">
                          <!-- Footnote Component -->
                          <div class="summit-footnote" data-summit-theme="dark">
                              <ul class="summit-footnote-container">
                                  <li class="summit-footnote-item"><div id="link_bar"><a href="https://mojo.redhat.com/docs/DOC-1172529" target=_blank>Documentation</a></div></li>
                              </ul>
                          </div>
                          <!-- Footnote Component -->
                      </div>
                  </div>
                  <div class="summit-group">
                      <div class="summit-group-body" data-summit-theme="dark" data-summit-layout="flex-between">
                          <div class="summit-image-embed" data-summit-align="center" data-summit-max-height="footer">
                              <div class="summit-image-embed-container">
                                      
        <!--<div class="media media-element-container media-default"><img class="media-element file-default summit-image-embed-img" alt="Summit logo" title="Red Hat Summit" src="https://www.redhat.com/cms/managed-files/summit-logo-74x35.png" width="74" height="35"></div>-->
                                  </a>
                              </div>
                          </div>
                      </div>
                  </div>
              </footer>
          </section>
      </div>
  </section>
