<div style="min-height: 10px;">
   <section class="summit-band" data-summit-band-background="transparent" data-summit-theme="dark" data-summit-band-type="hero2018">
      <div class="summit-band-container" data-summit-layout="8 4">
         <header class="summit-band-header">
                <h1 class="summit-band-header-title">Lab Information</h1>
            </header>
        </div>
    </section>
    <section class="summit-band" data-summit-band-background="white" data-summit-theme="">
      <div style="min-height: 10px;">
