/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=T02098;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-1;blueprint=SUMMIT-T02098-PrivateCloud-Summit-Lab-bp;bm=None;region=na_west' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=TC9818;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-1;blueprint=SUMMIT-TC9818-SecurityAutomationLab-2019-dev-bp-05042019-FINAL
None;bm=t
f;region=na_east' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=T1C7B2;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-1;blueprint=SUMMIT-Definitive-HandsOn-RHEL8-Workshop-20190501.1;bm=f;region=na_east' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=TBBD65;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-1;blueprint=SUMMIT-MBU-LAB-0.17.13-bp;bm=t;region=na_west' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=TFDD21;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-2;blueprint=SUMMIT-TFDD21-bp;bm=f;region=na_east' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=TC9818;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-2;blueprint=SUMMIT-TC9818-SecurityAutomationLab-2019-dev-bp-05042019-FINAL
None;bm=t
f;region=na_west' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=T9655E;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-2;blueprint=SUMMIT2019-azuregoldimage-bp;bm=t;region=na_east' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=TD09CB;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-2;blueprint=SUMMIT-appstream-dev-lab-bp.3;bm=f;region=na_east' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=T3748C;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-2;blueprint=GLOBAL-SYSENG-DEV-infra_migration_v1.1-bp;bm=t;region=na_west' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=T625B0;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-3;blueprint=SUMMIT-satellite6-2019-v47-restart-all-services;bm=t;region=na_west' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=TA39DD;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-3;blueprint=GENERAL-OCP3.11-minimal-summit-bp;bm=f;region=na_east' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=TC9818;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-3;blueprint=SUMMIT-TC9818-SecurityAutomationLab-2019-dev-bp-05042019-FINAL
None;bm=t
f;region=na_west' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=T9655E;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-3;blueprint=SUMMIT2019-azuregoldimage-bp;bm=t;region=na_east' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=TE9D49;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-3;blueprint=EMEA-PARTNERS-ansible_summit-v1.0-bp;bm=t;region=na_west' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=T02098;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-1;blueprint=SUMMIT-T02098-PrivateCloud-Summit-Lab-bp;bm=None;region=na_west' -g 40 -p 5 
/root/guidgrabber/bin/order_svc.sh -w https://spp.opentlc.com -u generic_summit -P 1b9d8ecd-74cc-42a4-b105-49493d9e4af0 -c Deployers -i 'Ravello Lab Deployer' -t 55 -n -d 'autostart=f;noemail=t;pwauth=t;check=t;expiration=7;runtime=8;labCode=T625B0;city=boston;salesforce=summit;notes=DeployedWithGuidGrabber;session=thursday-2;blueprint=SUMMIT-satellite6-2019-v47-restart-all-services;bm=t;region=na_west' -g 40 -p 5 
