
<link type="text/css" rel="stylesheet" href="/gg/gg.css" media="all">
<link rel="shortcut icon" href="/gg/favicon-new.ico" type="image/x-icon">
<title>Lab Manager</title>
<noscript>
    <div style="position: fixed; top: 0px; left: 0px; z-index: 3000;
                height: 100%; width: 100%; background-color: #FFFFFF">
        <p style="margin-left: 10px">
          JavaScript must be enabled in your browser for this site to work correctly!
        </p>
    </div>

</noscript>
<script>
if (!navigator.cookieEnabled)
{
  document.write(" \
    <div style='position: fixed; top: 0px; left: 0px; z-index: 3000;  \
                height: 100%; width: 100%; background-color: #FFFFFF'> \
        <p style='margin-left: 10px'> \
          Cookies must be enabled in your browser for this site to work correctly! \
        </p> \
    </div> \
  ");
}
</script>
<script>
function goBack() {
    window.history.back();
}
</script>

<style>
a:link {
    text-decoration: none;
    color: blue;
}

a:visited {
    text-decoration: none;
    color: blue;
}

a:hover {
    text-decoration: underline;
    color: blue;
}

a:active {
    text-decoration: underline;
    color: blue;
}
</style>

<link rel="stylesheet" href="/gg/w3.css">
<style>
.w3-btn {
  font-size: .5em;
}
</style>

<style>
    #link_bar a:link { color:#d0d0d0; }
    #link_bar a:visited { color:#c0c0c0; }
    #link_bar a:hover { color:#ffffff; background-color:#000060; }
    #link_bar a:active { color:#f0f0f0; background-color:#00ff00; }
</style>
