
<link type="text/css" rel="stylesheet" href="/gg/gg.css" media="all">
<link rel="shortcut icon" href="/gg/favicon-new.ico" type="image/x-icon">
<title>Lab GUID Assignment</title>
<noscript>
    <div style="position: fixed; top: 0px; left: 0px; z-index: 3000; 
                height: 100%; width: 100%; background-color: #FFFFFF">
        <p style="margin-left: 10px">
          JavaScript must be enabled in your browser for this site to work correctly!
        </p>
    </div>

</noscript>
<script>
if (!navigator.cookieEnabled)
{
  document.write(" \
    <div style='position: fixed; top: 0px; left: 0px; z-index: 3000;  \
                height: 100%; width: 100%; background-color: #FFFFFF'> \
        <p style='margin-left: 10px'> \
          Cookies must be enabled in your browser for this site to work correctly! \
        </p> \
    </div> \
  "); 
}
</script>

<script>
function goBack() {
    window.history.back();
}
</script>

<link rel="stylesheet" href="/gg/w3.css">
<style>
.w3-btn {
  font-size: .8em;
}
</style>

<style type="text/css" xml:space="preserve">
// BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
//A{font-family: Arial,Verdana,Helvetica, sans-serif;}
//B {     font-family : Arial, Helvetica, sans-serif;     font-size : 12px;       font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:14px; color:#660000; background-color:#ff0;}
</style>
